language: node_js
node_js:
- '6'
matrix:
    include:
        - env: SYSTEST=getting-started FC_TASK=systest
dist: trusty
before_install: ./.travis/before-install.sh
script: ./.travis/script.sh
sudo: false
notifications:
  pushover:
    api_key: ayq7zvsxc641sfna65njkik1x9y25b